# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ccf156c4ba439944691e12e3724f2cb6648a6898a415c0b6924a0de205f013607f5d8d825805aa100fa997a1f7fbbc393c44a28d6c72979919b7bf421d91566

test:
  secret_key_base: 6f2d108ea85dbfcd2dcba26aa96912dfd6766839dd25226f8e506bea60229ca44b01896acdf3800ea243e0371acf1a7283dccb5f268bcbebceefb11dfe9a860c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
